embedding_size: 64
latent_embedding: 64

n_layers: [ 1, 2, 3] # 3
reg_weight: [0] # [0.1, 0.01, 0.001, 0.0001, 0.00001]
learning_rate: [ 0.005, 0.007] # [1, 0.1, 0.01, 0.001, 0.0001]
train_batch_size: 4096
eval_batch_size: 4096

hyper_parameters: ["n_layers", "reg_weight", "learning_rate"]