# embedding_size: 64
# reg_weight: [2.0, 1.0, 1e-01, 1e-02, 1e-03, 1e-04, 1e-05]
# hyper_parameters: ["reg_weight"]

embedding_size: 64
learning_rate: [0.001] # , 0.0001]
reg_weight: [0.6] #[2,0, 1, 1e-01, 1e-02] # [2.0, 1.0, 1e-01, 1e-02] # , 1e-03, 1e-04, 1e-05]
hyper_parameters: ["learning_rate", "reg_weight"]
