embedding_size: 64
n_layers: 2
reg_weight: [0.001, 0] # [0, 0.00001, 0.0001, 0.001, 0.01, 0.1]
learning_rate: [0.0001, 0.001] # [0.001, 0.005, 0.0001] # , 0.0005, 
train_batch_size: 4096
eval_batch_size: 4096

hyper_parameters: ["reg_weight", "learning_rate"]

